# Generated by Django 2.2.2 on 2020-10-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.CharField(default='f16037cceec06647aaef1210cdd2d686', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
