# Generated by Django 2.2.2 on 2020-11-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='live_api',
            field=models.CharField(default='4a69c7efcb4c7b7f398be700672ab915', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='test_api',
            field=models.CharField(default='b88974d31346982163430c78a60920c7', editable=False, max_length=32, unique=True),
        ),
    ]
