# Generated by Django 2.2.2 on 2020-10-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201021_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.CharField(default='5f72ddf5f32378c7b801e6e56bc3f315', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
