# Generated by Django 2.2.2 on 2020-11-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201021_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.CharField(default='64064655fe32760d46307c1850eb1d75', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
