# Generated by Django 2.2.2 on 2020-11-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201109_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='live_api',
            field=models.CharField(default='f30d33a174a49fee1495b032dd037e9d', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='test_api',
            field=models.CharField(default='9b2518a52d68c8d87660241fccc67029', editable=False, max_length=32, unique=True),
        ),
    ]
