# Generated by Django 2.2.2 on 2020-11-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201109_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='live_api',
            field=models.CharField(default='7ce10985ee0cd582126cf76de8d4acf7', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='test_api',
            field=models.CharField(default='f59374dcd529b100c636a38a50bd843b', editable=False, max_length=32, unique=True),
        ),
    ]
