# Generated by Django 2.2.2 on 2020-11-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201105_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.CharField(default='a79e059ff2c57f3325ed6409bf89ec91', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
