# Generated by Django 2.2.3 on 2019-09-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190819_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='business',
            name='nuit',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='business',
            name='province',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
