# Generated by Django 2.2.2 on 2020-11-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201109_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='live_api',
            field=models.CharField(default='0bed3674c3858901aa3176321ae68e3f', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='test_api',
            field=models.CharField(default='42ca20d341b36b955beb47d51a8a1f81', editable=False, max_length=32, unique=True),
        ),
    ]
