# Generated by Django 2.2.2 on 2020-11-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201105_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.CharField(default='edbef50f2b92e64a4d62d706fa1d38ad', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
