# Generated by Django 2.2.3 on 2019-09-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190908_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.CharField(default='0ea904f8b369077bf91d2a310d654089', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
