# Generated by Django 2.2.2 on 2020-11-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20201105_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.CharField(default='006bf9e70541584aa40735d25bf23791', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
