# Generated by Django 2.2.3 on 2019-09-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190910_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.CharField(default='94ae6ddc083c2f7608623092a05d7dc4', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
