# Generated by Django 2.2.2 on 2019-11-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190910_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.CharField(default='180e15de8dfd5583fd65fc8d6bfdfcfc', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
