# Generated by Django 2.2.2 on 2020-11-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20201109_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='live_api',
            field=models.CharField(default='d59ec20a65d802b8973be9d1c709cf16', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='test_api',
            field=models.CharField(default='6cc1fd11db71e1fba0d37dea6b525367', editable=False, max_length=32, unique=True),
        ),
    ]
