# Generated by Django 2.2.2 on 2020-03-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20191106_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.CharField(default='b8315519973c31ebe82f1b3399c9f6fe', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
