# Generated by Django 2.2.2 on 2020-11-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20201109_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='live_api',
            field=models.CharField(default='b86b6f5e8bf76528234559ef79e09138', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='test_api',
            field=models.CharField(default='cf21106abae2420c6d8e0d325f4fd73a', editable=False, max_length=32, unique=True),
        ),
    ]
