# Generated by Django 2.2.2 on 2020-11-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20201110_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='live_api',
            field=models.CharField(default='74069aaa9eec4baba4b10f6edfd6d88c', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='test_api',
            field=models.CharField(default='57b929ec1de9eb50d5872820378ece86', editable=False, max_length=32, unique=True),
        ),
    ]
