# Generated by Django 2.2.2 on 2020-06-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200302_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.CharField(default='85472985bf87156723e4c6235a05c7fe', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
