# Generated by Django 2.2.2 on 2020-11-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20201110_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='live_api',
            field=models.CharField(default='ff8b0a94bd75e1b771b2c239efabda97', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='test_api',
            field=models.CharField(default='c0fd60400478ed434c0de6a4b8065b6f', editable=False, max_length=32, unique=True),
        ),
    ]
