# Generated by Django 2.2.2 on 2020-06-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200603_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.CharField(default='1c0cf110b9b0e2578c3020bc74a58f55', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
