# Generated by Django 2.2.2 on 2020-06-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200608_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.CharField(default='33f2c70395f9e1261a549117b8861b73', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
