# Generated by Django 2.2.2 on 2020-11-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20201116_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='live_api',
            field=models.CharField(default='e6d1f6df161d9777265e4886186a9871', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='test_api',
            field=models.CharField(default='c3bb0488383dd8e4c3b335c425035306', editable=False, max_length=32, unique=True),
        ),
    ]
