# Generated by Django 2.2.2 on 2020-06-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200608_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.CharField(default='dbc213a91343e55b9da6276004e2258e', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
