# Generated by Django 2.2.2 on 2020-06-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200609_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='is_startup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.CharField(default='ec89f360feef65b4ddc58f3a58749c12', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
