# Generated by Django 2.2.2 on 2020-06-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20200609_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.CharField(default='b025fafde2e182f396c747af1dce2322', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
