# Generated by Django 2.2.2 on 2020-06-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20200616_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.CharField(default='1a9e44c2e9eac73fe395cd1b78e8c13d', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
