# Generated by Django 2.2.2 on 2020-06-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20200629_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.CharField(default='50c01584f3dafc29802de0c0c997af56', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
