# Generated by Django 2.2.2 on 2020-06-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20200629_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.CharField(default='1fc0d0d6bfa65afb1011a7ffb9cfda60', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
