# Generated by Django 2.2.2 on 2020-06-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20200629_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.CharField(default='ea561695f672013692fdbf5e994b1182', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
