# Generated by Django 2.2.2 on 2020-09-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20200921_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='id',
        ),
        migrations.RemoveField(
            model_name='productionapi',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sandboxapi',
            name='id',
        ),
        migrations.AddField(
            model_name='business',
            name='public_key',
            field=models.CharField(default='6e6e483702cc5b87f2a861b46ff3c9e9ba4b63576c2f31bd964ad567a8ee581a', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='productionapi',
            name='api_key',
            field=models.CharField(default='94870df7d121f9fd157eca5131609e4f', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='sandboxapi',
            name='api_key',
            field=models.CharField(default='044135553151c213405ea3c2ee6760ea', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
