# Generated by Django 2.2.2 on 2020-09-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20200921_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='public_key',
            field=models.CharField(default='867176a355fbc9929c25cefd98131f713b1e55e4c2cbf07d3c23f99ee1041aea', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='productionapi',
            name='api_key',
            field=models.CharField(default='b58c867e61b53aedf7863484ba1ddb06', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sandboxapi',
            name='api_key',
            field=models.CharField(default='06af5278d4d8855878916c68a07ffed5', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
