# Generated by Django 2.2.2 on 2020-09-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20200921_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='public_key',
            field=models.CharField(default='fbf15aee319363100d7a94e3d3731912609f8ae638b1634f9b9ed4d3ad298dec', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='productionapi',
            name='api_key',
            field=models.CharField(default='cff0e8e8c49c6643462c42d4ce36b5f6', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sandboxapi',
            name='api_key',
            field=models.CharField(default='612ae63ffea335bbf81b42fd528b7a21', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
