# Generated by Django 2.2.2 on 2020-09-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20200921_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='public_key',
            field=models.CharField(default='d5e6dc53fa801f9d26e398492442bc7ef8a517245a79818bb074ef4f18d92284', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='productionapi',
            name='api_key',
            field=models.CharField(default='12fb2ceadf46bb7f5040747e0cbb8f0d', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sandboxapi',
            name='api_key',
            field=models.CharField(default='80a433ad9102c30b2c5951dcfc5e35b0', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
