# Generated by Django 2.2.2 on 2020-09-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20200921_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='public_key',
            field=models.CharField(default='0b27a3b7bb1c8a9e25f0046e8a780fe5e6fe8aad95fc48355ccafcd2640ba2e1', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='productionapi',
            name='api_key',
            field=models.CharField(default='020fafb827f530c8d1f44b31f6565b18', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sandboxapi',
            name='api_key',
            field=models.CharField(default='664cf35041f2b161f5c36d33584ac094', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
