# Generated by Django 2.2.2 on 2020-09-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20200921_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='public_key',
            field=models.CharField(default='119bd2cb5fa9ce8abb23b00bf1514547d594679ac071c89301a6c63cf76b3757', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='productionapi',
            name='api_key',
            field=models.CharField(default='f99cba6fbeae3f41edaf3cd12d47b02c', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sandboxapi',
            name='api_key',
            field=models.CharField(default='ce4929fdcdf839d6e10aa480a594e5aa', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
