# Generated by Django 2.2.2 on 2020-09-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_auto_20200921_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='nuit',
            new_name='nuqit',
        ),
        migrations.AlterField(
            model_name='business',
            name='public_key',
            field=models.CharField(default='1d0bb25080e01e936f08a5856c0c43d2eb7d54462be3c2210f559ee40f07a863', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='productionapi',
            name='api_key',
            field=models.CharField(default='5aef396311bcee027817688b4e7c6a47', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sandboxapi',
            name='api_key',
            field=models.CharField(default='16e489b900ad8a283035571b85b9e4ba', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
