# Generated by Django 2.2.2 on 2020-09-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_auto_20200921_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='public_key',
            field=models.CharField(default='3449f6b491bd9819cabeabfca45f23c1a3c4a0b9180b21778508f59f03631519', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='productionapi',
            name='api_key',
            field=models.CharField(default='c59ab3fd9060a46cba865822999f7346', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sandboxapi',
            name='api_key',
            field=models.CharField(default='2fe4e1127713f55de812e8300cd2e227', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
