# Generated by Django 2.2.3 on 2019-09-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('public_key', models.TextField()),
                ('website', models.URLField()),
            ],
        ),
    ]
