# Generated by Django 2.2.3 on 2019-07-29 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_sender', models.CharField(max_length=15)),
                ('mount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('last_day', models.DateTimeField()),
            ],
        ),
    ]
