# Generated by Django 2.2.2 on 2019-06-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('public_key', models.TextField()),
                ('mpesaReturn', models.TextField()),
            ],
        ),
    ]
