# Generated by Django 2.2.3 on 2019-08-19 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='phone_number',
            new_name='token',
        ),
    ]
