# Generated by Django 2.2.2 on 2020-06-08 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='xpayMpesa',
            new_name='Transaction',
        ),
    ]
