# Generated by Django 2.2.2 on 2020-11-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='api',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
