# Generated by Django 2.2.2 on 2020-11-10 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0002_transaction_api'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='token',
        ),
    ]
