# Generated by Django 2.2.2 on 2020-06-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0002_auto_20200608_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='contact',
            new_name='phone_number',
        ),
    ]
