# Generated by Django 2.2.3 on 2019-07-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0003_auto_20190717_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='website',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
