# Generated by Django 2.2.2 on 2020-06-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0003_auto_20200608_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.ForeignKey(on_delete='CASCADE', related_name='transaction', to='account.Token'),
        ),
    ]
