# Generated by Django 2.2.2 on 2020-06-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0004_auto_20200629_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
