# Generated by Django 2.2.3 on 2019-07-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0005_auto_20190718_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='mpesaReturn',
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
