# Generated by Django 2.2.3 on 2019-07-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0006_auto_20190721_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mpesaReturn',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
