# Generated by Django 2.2.2 on 2020-09-29 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0006_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
