# Generated by Django 2.2.2 on 2020-11-05 01:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0008_auto_20201105_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
