# Generated by Django 2.0.2 on 2020-04-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
