# Generated by Django 2.0.2 on 2020-04-06 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_remove_post_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
