# Generated by Django 2.0.2 on 2020-04-06 11:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20200406_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
