# Generated by Django 2.0.2 on 2020-04-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_auto_20200406_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
