# Generated by Django 2.2.2 on 2020-10-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='first_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
