# Generated by Django 2.2.2 on 2020-10-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0003_remove_transaction_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='token',
        ),
    ]
