# Generated by Django 2.2.2 on 2020-10-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0005_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='name',
        ),
        migrations.AddField(
            model_name='website',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
