# Generated by Django 2.2.2 on 2020-09-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='public_key',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
